"""add superuser flag

Revision ID: a15efc303e86
Revises: 351ffb92c64c
Create Date: 2026-09-05 19:51:16.025936
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a15efc303e86"
down_revision: str | None = "351ffb92c64c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("is_superuser", sa.Boolean(), server_default="false", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_superuser")
    # ### end Alembic commands ###
