"""add authentication version

Revision ID: ad3efeb5c3be
Revises: a15efc303e86
Create Date: 2026-09-06 00:06:38.751251
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "ad3efeb5c3be"
down_revision: str | None = "a15efc303e86"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("auth_version", sa.Integer(), server_default="0", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "auth_version")
    # ### end Alembic commands ###
